### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by JD-2006** [34j/so-vits-svc-fork-paperspace#1]
[19:10:41] Version: 2.1.5
[19:10:56] Version: 2.1.5
[19:10:59] {'train': {'log_interval': 100, 'eval_interval': 200, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 10240, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/44k/train.txt', 'validation_files': 'filelists/44k/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050, 'contentvec_final_proj': False}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 768, 'n_speakers': 200, 'type_': 'hifi-gan'}, 'spk': {'angelena': 0}, 'model_dir': 'logs/44k'}
[19:10:59] Added key: store_based_barrier_key:1 to store for rank: 0
[19:10:59] Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
[19:10:59] /usr/local/lib/python3.10/site-packages/so_vits_svc_fork/modules/synthesizers.py:81: UserWarning: Unused arguments: {'n_layers_q': 3, 'use_spectral_norm': False}
  warnings.warn(f"Unused arguments: {kwargs}")

[19:10:59] Decoder type: hifi-gan
Traceback (most recent call last):
  File "/usr/local/bin/svc", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/so_vits_svc_fork/__main__.py", line 128, in train
    train(
  File "/usr/local/lib/python3.10/site-packages/so_vits_svc_fork/train.py", line 53, in train
    mp.spawn(
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.10/site-packages/so_vits_svc_fork/train.py", line 100, in _run
    net_g = SynthesizerTrn(
  File "/usr/local/lib/python3.10/site-packages/so_vits_svc_fork/modules/synthesizers.py", line 113, in __init__
    self.dec = Generator(h=hps)
  File "/usr/local/lib/python3.10/site-packages/so_vits_svc_fork/modules/decoders/hifigan/_models.py", line 268, in __init__
    self.resblocks.append(resblock(h, ch, k, d))
TypeError: ResBlock1.__init__() takes from 2 to 4 positional arguments but 5 were given

**Comment by 34j** [comment]
Perhaps it has been fixed. Please change to `BRANCH = "none"` and try again.

**Comment by JD-2006** [comment]
Re-installed in new ENV and seems to work now. Cheers.
